name: smart_text_flutter
description: "A Flutter plugin used to detect links in texts using NSDataDetector on iOS and TextClassifier on Android"
version: 0.3.4
homepage: https://github.com/developerjamiu/smart-text-flutter

environment:
  sdk: ">=3.2.5 <4.0.0"
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2
  url_launcher: ^6.3.1
  url_launcher_ios: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.developerjamiu.smart_text_flutter
        pluginClass: SmartTextFlutterPlugin
      ios:
        pluginClass: SmartTextFlutterPlugin
